### ISSUE TITLE
Echo 360 file names not using enclosure info

### ISSUE THREAD

**Issue by witeshadow** [dvehrs/podget#10]
For the podcast url: [https://dl.ipfw.edu:8443/ess/feed?id=18ae84db-71bd-4cd8-b896-fe156df4f427&type=M4V]

I have been unable to configure it so that I get sane file names. Either they all have the same exact name, or they have names that don't really tell me the date as noted in the feed.

**Comment by dvehrs** [comment]
I'm not sure it is possible for Podget to get sane filenames for the items in this feed.  Unfortunately they do not use anything that I have been able to use within the Podget bash script.

They do use a separate tag to declare the publish date but I can't use that because I'm limited to what can be derived from the enclosure url.  If they were to use a location or content disposition tag then Podget could use it, but they don't so it appears that we are limited to what is in the URL.

Now, you will need to download the latest updated version from the DEV or MASTER branches from Github, as they fix a small error that this solution will run into.  However once, you've downloaded and installed that version then we should be able to configure Podget so that each file has a unique filename.  What you need to do is enable FILENAME_FORMATFIX4=1.  

Now this may cause problems with other feeds that you are downloading so you may want to create a new podgetrc just for this one feed.    To do so, run:

    podget --create-config podgetrc.ipfw.edu    (name it whatever you want)

It will then create a new podgetrc in your user configuration directory (generally $HOME/.podget).

Then edit that file to have its own serverlist (maybe serverlist.ipfw.edu) that is also in your configuration directory and that has FILENAME_FORMATFIX4=1.  For the serverlist file, it should have the feed URL for this item.

Then to run podget with the new configuration, just run:
  podget -c podgetrc.ipfw.edu  

This will download all the items and make sure they have unique filenames.  Now we are not entirely limited to just the filename because each file is given the date that it was uploaded.  So if you run 'ls -ltr' on the directory that they are saved, you will see that each file has it's upload date as the last modified time.     

Now, I've clipped this output to highlight the important parts we care about:

ls -ltr
  95M Jan 13  2015 1238fb10-07ff-473e-95c1-530321b87eeb_audio-vga.m4v
 100M Jan 15  2015 bef73448-d2e9-4d5f-9640-3663a0429439_audio-vga.m4v
  99M Jan 20  2015 43c3ec16-912a-43fc-87d9-d00e9d0116a9_audio-vga.m4v
 105M Jan 22  2015 7b7e1021-d73a-40fc-a6aa-24fa49456556_audio-vga.m4v
 101M Feb 10  2015 652c0334-43b4-43a8-aacc-cbed84e923d5_audio-vga.m4v
 103M Feb 12  2015 f6872a4c-c6ca-4cdc-b01b-0bdfb9811ffb_audio-vga.m4v
  89M Feb 17  2015 5f8cfab3-d3f3-4871-926a-031331e9c79a_audio-vga.m4v
 108M Feb 19  2015 5ef8fd0f-63cb-427a-b3bc-169e40c2c5df_audio-vga.m4v
 103M Feb 24  2015 f7b18c23-41cf-4109-a1ec-5776f2388c5c_audio-vga.m4v
 100M Feb 26  2015 74af57c4-00ab-44a2-b7b7-4ba7134af482_audio-vga.m4v
  97M Mar  3  2015 2bfa4db5-aa0d-47ac-98e8-11ab75b37c7f_audio-vga.m4v
  99M Mar  5  2015 50718aed-3c60-4658-8939-cb624fa33d26_audio-vga.m4v
 102M Mar 17  2015 61c9298b-3a21-4f39-9d9d-9de186f18299_audio-vga.m4v
  94M Mar 19  2015 649a9a3b-70ba-42d8-985c-bd5601dac253_audio-vga.m4v
 101M Mar 24  2015 6700601e-a9ab-484f-a730-f38be8497fe9_audio-vga.m4v
  99M Mar 26  2015 07b8b8d0-dc45-4e3b-8644-cf5dd6a085b6_audio-vga.m4v
  99M Mar 31  2015 8dc33827-a8fe-4460-bebb-0b53dcf2a02b_audio-vga.m4v
  99M Apr  2  2015 01e7c840-0296-4343-aeb4-69b004e823f8_audio-vga.m4v
 100M Apr  7  2015 ce0e78c9-3420-4777-8ee5-8586465485ba_audio-vga.m4v
 102M Apr  9  2015 3e091a93-7a9f-4adc-9f34-4bb991c2e070_audio-vga.m4v
 102M Apr 14  2015 56a7b67d-afdf-4212-8abe-b0910fce3dee_audio-vga.m4v
 101M Apr 16  2015 3837927b-024b-4fc4-9737-f62f76d3e628_audio-vga.m4v
 106M Apr 21  2015 86a0c13e-36a6-4f36-8dd7-fe00fc24a118_audio-vga.m4v
  96M Apr 23  2015 782aac20-7dc9-4b70-9201-a134673223b5_audio-vga.m4v
  99M Apr 28  2015 f2dc7d36-81fa-43b5-9e20-87a4cef4285c_audio-vga.m4v
 100M Apr 30  2015 434ab184-4573-46e8-9e14-b07c927a755a_audio-vga.m4v

As you can see, we have unique filenames and unique dates for each file.   But that's not a very usable filename, so we can make it a little better.  We want to embed that modified date in each filename.  To do so, we run the following command on the directory:

for FILE in $(ls -tr); do mv ${FILE} $(date -r ${FILE} '+%Y%m%d').m4v; done

Now if we look at the directory listing (once again trimmed to just what we care about):

ls -ltr
  95M Jan 13  2015 20150113.m4v
 100M Jan 15  2015 20150115.m4v
  99M Jan 20  2015 20150120.m4v
 105M Jan 22  2015 20150122.m4v
 101M Feb 10  2015 20150210.m4v
 103M Feb 12  2015 20150212.m4v
  89M Feb 17  2015 20150217.m4v
 108M Feb 19  2015 20150219.m4v
 103M Feb 24  2015 20150224.m4v
 100M Feb 26  2015 20150226.m4v
  97M Mar  3  2015 20150303.m4v
  99M Mar  5  2015 20150305.m4v
 102M Mar 17  2015 20150317.m4v
  94M Mar 19  2015 20150319.m4v
 101M Mar 24  2015 20150324.m4v
  99M Mar 26  2015 20150326.m4v
  99M Mar 31  2015 20150331.m4v
  99M Apr  2  2015 20150402.m4v
 100M Apr  7  2015 20150407.m4v
 102M Apr  9  2015 20150409.m4v
 102M Apr 14  2015 20150414.m4v
 101M Apr 16  2015 20150416.m4v
 106M Apr 21  2015 20150421.m4v
  96M Apr 23  2015 20150423.m4v
  99M Apr 28  2015 20150428.m4v
 100M Apr 30  2015 20150430.m4v

Now we have sortable sequential filenames.   

If you use podget to download later files and they have the unique but LONG filename, feel free to run the for loop again.  It will simply error for any already renamed files while renaming any new ones.  At least that's what it does for my testing.  

Now maybe for the future we can figure out how to make podget rename the file based on the modification date automatically.  But I'm not sure how yet....

**Comment by dvehrs** [comment]
OK. good news.  I was watching a show about Golebki Tepe and I conceived of a way to address this within podget so you don't need to jump through the hoops I outlined above.

Step 1:  Download an updated copy of podget from the DEV branch.

Step 2.  Update your server list for the desired feed to include a new tag
https://dl.ipfw.edu:8443/ess/feed?id=18ae84db-71bd-4cd8-b896-fe156df4f427&type=M4V CATEGORY NAME OPT_FILENAME_RENAME_MDATE

The 'magic' is in the 'OPT_FILENAME_RENAME_MDATE, it causes each file that is downloaded to be prefixed with the date & time of the last modification of the file.  So instead of having 26 files all named "audio-vga.m4v", we get individual files like below.

Step 3:  Rerun podget to download the files and automatically rename them.  You can either delete all the links from your COMPLETED log or you can tell podget to redownload them even if they are marked as already done.  If you do the second, make sure to comment out any other feeds in your serverlist that you don't want to completely redownload.

   Command:   podget --force     

Now, if you look in your download directory, you should see something like this  (once again trimmed of the boring information):

ls -ltr
  95M Jan 13  2015 20150113_14h19m_audio-vga.m4v
 100M Jan 15  2015 20150115_13h22m_audio-vga.m4v
  99M Jan 20  2015 20150120_12h36m_audio-vga.m4v
 105M Jan 22  2015 20150122_13h38m_audio-vga.m4v
 101M Feb 10  2015 20150210_12h21m_audio-vga.m4v
 103M Feb 12  2015 20150212_12h10m_audio-vga.m4v
  89M Feb 17  2015 20150217_12h10m_audio-vga.m4v
 108M Feb 19  2015 20150219_12h26m_audio-vga.m4v
 103M Feb 24  2015 20150224_12h38m_audio-vga.m4v
 100M Feb 26  2015 20150226_12h39m_audio-vga.m4v
  97M Mar  3  2015 20150303_12h33m_audio-vga.m4v
  99M Mar  5  2015 20150305_12h32m_audio-vga.m4v
 102M Mar 17  2015 20150317_12h53m_audio-vga.m4v
  94M Mar 19  2015 20150319_12h45m_audio-vga.m4v
 101M Mar 24  2015 20150324_12h43m_audio-vga.m4v
  99M Mar 26  2015 20150326_12h38m_audio-vga.m4v
  99M Mar 31  2015 20150331_12h14m_audio-vga.m4v
  99M Apr  2  2015 20150402_12h13m_audio-vga.m4v
 100M Apr  7  2015 20150407_12h14m_audio-vga.m4v
 102M Apr  9  2015 20150409_12h36m_audio-vga.m4v
 102M Apr 14  2015 20150414_12h15m_audio-vga.m4v
 101M Apr 16  2015 20150416_12h08m_audio-vga.m4v
 106M Apr 21  2015 20150421_12h13m_audio-vga.m4v
  96M Apr 23  2015 20150423_12h48m_audio-vga.m4v
  99M Apr 28  2015 20150428_12h31m_audio-vga.m4v
 100M Apr 30  2015 20150430_12h09m_audio-vga.m4v

And we've got sortable filenames for a lot less work than I outlined above.  I still need to test it with a variety of feeds to be sure I haven't broken anything but so far the results are encouraging.  

If you test it, let me know how it works out for you.

**Comment by dvehrs** [comment]
OK, this option has been pushed to the latest version.

Enjoy!
