### ISSUE TITLE
Podget fails on valid Atom feed

### ISSUE THREAD

**Issue by hugh-m** [dvehrs/podget#11]
Podget 0.7.13-1 on Debian Sid

I have been using Podget happily for several years.

I scraped a page of podcasts to a valid Atom feed http://www.jetvol.com/scripts/atomgenerate-jff and was surprised when Podget reported "No enclosures in feed" and exited.

Would it be hard to make Podget work with Atom podcast feeds?

**Comment by dvehrs** [comment]
OK, it appears there is a difference in how the feeds we used up to this time have handled enclosures and how this Atom feed does.

For example, what I've generally been looking for in the feed is similar to:

`<enclosure length="22504719" type="audio/mpeg" url="http://traffic.libsyn.com/completeliberty/CLpodcast1.mp3" />`

But what this Atom feed has is:

`<link rel="enclosure" type="audio/mpeg" title="Journal en Français Facile 2016-05-08" length="720" href="http://telechargement.rfi.fr/rfi/francais/audio/jff/201605/journal_francais_facile_20h00_-_20h10_tu_20160508.mp3"/>`

So we see two big differences.  

First is the use of the 'enclosure' tag vs using the 'rel' (relationship) tag for a link.

Second, is the use of 'url=' vs 'href='.   

Parsing the input file for these two tags has the potential to make podget run a lot slower for this step.  Is that a significant issue on modern hardware?  I don't know but it concerns me.  

Plus watching for these two tags, do we also need to watch for 'type="audio/mpeg"' and all the variations of what can be acceptable files (MP3, OGG, etc.)?  To be sure we don't download files we don't care about....

Is this feed only available as an Atom feed or can it also be found as an RSS?  In my experience, a lot of feeds do not limit themselves to one path for distribution but make it available in a variety of formats.  The trick is to find the right feed.  

I will let this one float around my brain for a while, maybe it will surprise me with a workable solution.  Wish me luck!

Dave

**Comment by dvehrs** [comment]
A quick google search lead me to this feed that appears to have many of the same items but is in a format that Podget expects.  Will it provide what you're looking for?

http://www1.rfi.fr/radiofr/podcast/journalFrancaisFacile.asp

**Comment by dvehrs** [comment]
OK, I just tested the above feed in Podget and it downloaded 9 items for me without a problem.  If it works for you, I think finding the correct feed would appear to be the simplest option.

Dave

**Comment by hugh-m** [comment]
Thanks.  I hadn't found that feed. It's not linked from the actual podcast page.

My point is, tho, that the feed I provided is a perfectly valid feed. Are Atom podcast feeds really so rare that you have never encountered them? If so, that's interesting in itself.

I haven't tried my feed in any other podcatchers because Podget is the only one I have installed.

Thanks for your work on Podget, I make use of it every day.

**Comment by dvehrs** [comment]
It is a valid Atom feed but for the reasons I outlined above, I believe it will have potentially adverse affects on the performance of podget.  

I'm not always right and you can prove me wrong.  Not to long ago, Nicolae Sandor proved to me that we could use the filename attribute from the content-disposition tag provided by the server.  With a little work, we created a solution that worked within podget and didn't significantly affect performance.

You have the full script of podget and you can see how it works.  If you think it can be added, feel free to submit an idea.  The enclosure tags are currently extracted at approximately line 1865 (version 0.7.14).  

Now I haven't tried any Atom feeds but a couple quick google searches lead me to believe that we probably should add support for them to Podget.    

Here's a basic comparison of RSS & Atom:
http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared

The interesting part is in the Element Comparison Table.   Now, assuming that Atom feeds respect the use of the 'rel="enclosure"' and always follow it with an 'href=" then we may be able to work with it.  

But we're probably going to need a variety of Atom feeds from different sources to test with.....

**Comment by dvehrs** [comment]
OK, we definitely need a variety of Atom feeds to test.  I've been able to put together a simple pattern that works for the feed you submitted above and it appears to not cause any issues with the RSS feeds in my test list.  So far so good and I might have been overly negative about its possible inclusion  But we need more feeds to tweak out the pattern matching to be as reliable as the RSS statements.

You can find the latest test version in the 'dev' branch.  Feel free to test it.

**Comment by dvehrs** [comment]
OK, I've found the first potential issue.  For Atom it is possible to link to multiple enclosures in different languages for each item and the example I've found has them all with the same filename.  So it may be necessary to add the ability to filter on the 'xml:lang=' tag.

**Comment by dvehrs** [comment]
OK more documentation on potential issues with Atom feeds....
https://www.ibm.com/developerworks/xml/library/x-atom10/index.html

In the "Support for enclosures" section:

> While podcasting is rapidly growing in popularity, the RSS 2.0 enclosure tag has at least one very significant limitation that has proven to be an annoyance to podcasters: RSS allows only one enclosure tag per item. This means that podcast producers who wish to make their audio downloads available in multiple formats (such as MP3, BitTorrent, or WMA) must offer separate feeds for each format they wish to offer. Atom, on the other hand, allows any single entry to contain multiple enclosures, each with an associated media type attribute that makes it possible for podcasters to produce a single feed containing all of the formats they distribute.

So we have the potential for multiple items being declared for every enclosure.  For podget to function as it was planned, we need to find a way to filter that down to just the items the user cares about.

We may have to fork the development of this thread off the 'dev' branch onto its own branch because it may take us a while to account for all the possibilities.

**Comment by dvehrs** [comment]
Pushed work on these ideas to branch dev-atom

**Comment by dvehrs** [comment]
OK, basic detection of RSS or Atom feed, and selection of enclosures enabled.   Need to add filtering on the Atom chain based on allowed tags.  The list of potential types is huge but most of them are not likely to be targeted by podget (mostly audio or video types) so we can easily filter them away.  This should actually be fairly easy.  After that we need to enable a filter that allows the user to specify what types to limit so that they don't download too many.  

https://www.iana.org/assignments/media-types/media-types.xhtml

Then as a subsequent test, we need to filter the list by preferred language.

And then we need to find whatever else it might be desirable to filter on that exists within the link line.

**Comment by hugh-m** [comment]
Can all that be done with sed regular expressions? Might it be time to introduce an xml parsing dependency to Podget?

**Comment by dvehrs** [comment]
If you have an XML parsing dependency to suggest then do so.

However as a general rule, I prefer to minimize dependencies.  Keeping up with the changes in other projects can be a task unto itself and it makes cross-distribution support more challenging as not all packages will be available for all distributions.

**Comment by dvehrs** [comment]
OK, what we really need are more Atom feeds.  I currently have 32 RSS feeds and 2 Atom feed to test with.  So far, the script is reliably detecting the type but it is a limited data set.  

The second feed I found also seems to use only one enclosure per item, so we really need to find a feed with multiple enclosures either because of type or language.

I'm currently downloading the second Atom feed in both Atom & RSS to see if there are any differences in results.

**Comment by dvehrs** [comment]
OK, I found two Atom feeds with PDFs, MP3s and MP4s.  So I've got basic type filtering in place on the dev-atom branch.  However it is not truly functional yet because I have the loops cut short with lots of output to debug the filtering.

I'm currently testing against:
http://www.lse.ac.uk/assets/richmedia/webFeeds/publicLecturesAndEvents_AtomAllMediaTypesAllitems.xml
http://www.lse.ac.uk/assets/richmedia/webFeeds/publicLecturesAndEvents_AtomAllMediaTypes2016.xml

So one is a subset of the other but so far they're the only feeds I've found with multiple types and lots of items.  The top feed has 423 PDFs, 2670 MP3s and 859 MP4s.  

What we could really use is a feed with multiple languages.  If we can enable filtering for that, then we probably have enough to bump support into the master branch.

**Comment by hugh-m** [comment]
Here is a quick test feed with three languages and two formats (the files are empty, tho)

http://www.jetvol.com/scripts/test-feed-languages

**Comment by dvehrs** [comment]
Thanks for the feed.  It helped test the various options available.

OK, I just uploaded mostly complete support for Atom feeds to the dev-atom branch for testing.  So far it appears to be working here and I haven't found any old feeds that fail to work...although I haven't tested that many.    But it's there and ready to test.  Have at it!

Enjoy,

Dave

**Comment by hugh-m** [comment]
Seems to work fine. Thanks very much. Podget was the first podcatcher I used and it perfectly suited the way I like to consume podcasts.

**Comment by dvehrs** [comment]
OK, I think there has been as much testing as we can do within this small group, so I've merged the changes into 'dev' and 'master'.   I've also marked it for release as version 0.8

Here's hoping that I haven't introduced some bugs that I missed testing for....
