### ISSUE TITLE
mp3_dest-id_316808

### ISSUE THREAD

**Issue by capturts** [dvehrs/podget#15]
I have several padcast that the rss feed is on libsyn.com and just recently the mp3's have been downloading with an odd ending:
xxxxx.mp3_dest-id_316808
It even messes up the file extension. They used to be fine. Is there a filename cleanup that will work for this.

**Comment by DrAzraelTod** [comment]
I've seen such stuff too, looked into the source of the feed and the files are named like this in the URL. So it's not podgets fault.

I'm currently using ffprobe to get titles from metadata and just display that. You could use/adapt that to rename the files, but i wouldn't include it in podget, since it'd introduce ridiculous dependency hell.

    #!/bin/sh
    for file in *
    do
      title=`ffprobe 2> /dev/null -show_format $file | grep TAG:title= | cut -d '=' -f 2` &&
      printf "%$1s %s\n" $file "$title";
    done;

**Comment by dvehrs** [comment]
I could look into this but I would need the feed URL to get started.   It's hard to work on from just a few line description.

Although what DrAzraelTod suggests might be a good solution but I can't say for sure until I have a feed to play with.

**Comment by dvehrs** [comment]
OK, I've looked at the patch and I'm considering it.   In the past this has not been an issue for most the feeds I download because I enable FILENAME_FORMATFIX=1 in my podgetrc.   That first fix takes whatever comes after the ? and puts it before the file extension.

So if we enabled debugging and lots of verbosity, we see the change on one item like so:
ORIGINAL FILENAME:      TANIS_EPISODE_210_-_The_Voice_in_the_Darkness.mp3?dest-id=316385
DEBUG -- FILENAME FORMAT FIXED: TANIS_EPISODE_210_-_The_Voice_in_the_Darkness?dest-id=316385.mp3
MODIFIED FILENAME:      TANIS_EPISODE_210_-_The_Voice_in_the_Darkness_dest-id_316385.mp3

Now this does keep the dest-id as part of the filename but makes it usable by most media players.

On the other hand, I can understand why it may be preferable to simply discard the whole dest_id portion.   So I'm still considering your patch but it conflicts with my long term goals to get rid of the FILENAME_FORMATFIXes.  So I'm torn...
