### ISSUE TITLE
Playlist for entire podcast

### ISSUE THREAD

**Issue by capturts** [dvehrs/podget#16]
Would it be possible to add an option that would update/create a m3u playlist for an entire podcast - not just for newly downloaded episodes. It would generate it for every episode from oldest to newest. One playlist for each podcast.

**Comment by DrAzraelTod** [comment]
I've a secondary script that does that for me. called it m3u.sh and run it via cronjob on some dirs
Most part of it is excluding file extensions that I don't want to included in my playlist.

    #!/bin/bash
    dir="$1"
    #echo "Create playlist for $1 ..."
    if [[ $2 ]]; then list="$2"; else list="$1"; fi
 
    #!/bin/sh
    dir="$1"
    #echo "Create playlist for $1 ..."
    if [[ $2 ]]; then list="$2"; else list="$1"; fi
    pushd . 2>&1 >/dev/null
    find . -type f \
            -not -name "*.m3u" \
            -and -not -name "*.asx" \
            -and -not -name "done" \
            -and -not -name "errors" \
            -and -not -name "*.html" \
            -and -not -name "*.js" \
            -and -not -name "*.swp" \
            -and -not -path "*/.git/*" \
            -and -not -name "*.sh" \
            -and -not -name "*.md" \
            -and -not -name "*.tgz" \
            -and -not -name ".*" \
            -and -not -empty \
            > "$list" -exec ls -1rt "{}" +;
    wc -l "$list"
    sed -i 's/ /%20/g' "$list"
    popd 2>&1 >/dev/null

**Comment by capturts** [comment]
Thanks for the reply, how will it know which order the episodes go in?

**Comment by DrAzraelTod** [comment]
it won't

or better: the order depends on how "find" orders the files

**Comment by dvehrs** [comment]
DrAzraelTod has some good ideas for producing a feed list here but we can add to it.

If you add the OPT_FILENAME_RENAME_MDATE, it will attempt to add the modification date of the file to the beginning of the filename in a YYYYMMDD_HHhMMm_(filename) format.  If the original modification time is not available, then it will commonly be the date/time that the file was downloaded.

Then the files will be sortable by date and should make a some-what sane list.

**Comment by dvehrs** [comment]
OK,  I'm undecided if this function should be integrated within Podget or if we already do too much.  I've created a simple test script that can be found in the 'dev' branch in the SCRIPTS directory.  It is called podget_update_playlists that creates updated playlists for each feed each time its run.  

On my tests, it appears to reliably list the items on each playlist from oldest to newest.  Not sure if that should be a configurable item or not. 

So far it only does M3U playlists but it might be possible to integrate the ASX conversion

This script started with DrAzaelTod's inspiration and then got complexity added as I worked to integrate it with existing Podget configuration files to keep usage as simple as possible.. Because of the shared items it may be best to integrate it to Podget.

**Comment by dvehrs** [comment]
Oh and this new script does not require the usage of OPT_FILENAME_RENAME_MDATE, it works from the file modification dates stored in the filesystem.

**Comment by dvehrs** [comment]
OK, discovered small issue with the example in the SCRIPTS directory.  If a category directory has no feed directories in it, the script will exit with an error.  So I'm looking for a simple way to address that before we can consider working it into the parent podget.

**Comment by dvehrs** [comment]
Sorry for the small delay getting onto this but I think I may have worked out an way to do it for individual feeds.  I've uploaded by test version to the dev branch.

Basically it works by the user adding the tag OPT_FEED_FULL_PLAYLIST to the feed lines that they desire playlists created (or updated) for in their serverlist.   This will create (or update) the playlist stored in the base of the LIBRARY directory with all items for that feed.

An example of how it would look in the serverlist file is:
http://www.2600.com/oth.xml 2600 Off the Hook OPT_FEED_FULL_PLAYLIST

And the playlist would be named:  PLAYLIST_Off_the_Hook.m3u

Anyway, like I said this is in the dev branch and ready for testing.  If all goes well with my own testing, I should be ready to push a release soon.

Dave

**Comment by dvehrs** [comment]
OK, small change.

Rather than having the playlists in one order, it now supports them in two.

Replaced the OPT_FEED_FULL_PLAYLIST tag with: OPT_FEED_PLAYLIST_NEWFIRST and OPT_FEED_PLAYLIST_OLDFIRST.  This allows the user to configure the order that they want to see the items from a feed added to its playlist.  For my own use this is handy because some feeds I mostly care about what is recent and others I want to see the whole chapter by chapter listing.

**Comment by dvehrs** [comment]
One small followup change.  Moved the creation of these playlists to after the cleanup function.  It's tested well here, so I merged it with the master branch and released version 0.8.4.   Hopefully this works well for everyone!
