### ISSUE TITLE
Garbage in podcast names

### ISSUE THREAD

**Issue by Oflameo** [dvehrs/podget#33]
Is there a a way to turn off garbage that clobbers up some podcast names like a signature.

This feed is clobbered up with dumb names http://tv.infowars.com/podcast/pod.php?category=dailyshows, but this feed doesn't but doesn't have the same set http://rss.infowars.com/. 

Is there anything I can do to fix it locally?

**Comment by dvehrs** [comment]
OK when I download the first two items on the feed, I have the following filenames that are converted.

From the URLs:
20170912_Tue_WarRoom.mp3?saison=1505321461&signature1=bac1b802c4f0719e9042a112ed3e436e
20170912_Tue_Alex.mp3?saison=1505321461&signature1=6bd4ccec0e2721fcfa5fd7f953ca12b8

Converted to:
mp3_20170912_Tue_WarRoom_saison_1505321461_signature1_bac1b802c4f0719e9042a112ed3e436e.mp3
mp3_20170912_Tue_Alex_saison_1505321461_signature1_6bd4ccec0e2721fcfa5fd7f953ca12b8.mp3

Now there are two items happening here.  First the 'mp3_' is being added to the filename because FILENAME_FORMATFIX4 is enabled.  Disable it and the date will be the first part of the name.

The second part is everything after the '?' in the URL filename is being appended to the saved filename.   In many cases this is valuable information for identifying the individual items but I don't think that is the case here.  In this case, removing it automatically as part of Podget may cause issues with other feeds but we can manually clean it up fairly easily.

Once Podget has finished it's run, we can run the following command on the directory of downloaded files.

```
for file in *saison*; do cp "${file}" "$( echo ${file} | sed 's/\(.*\)_saison_.*/\1.mp3/')"; done
```

This looks for the part of the filename that starts with '_saison_' and removes it and everything after it from each filename, then puts the '.mp3' back.  

After that, the filenames we have left are:
20170912_Tue_Alex.mp3                                                                   
20170912_Tue_WarRoom.mp3   

Now this is a fairly crude fix but it works for this individual case.  Is that what you hoped to accomplish?

**Comment by Oflameo** [comment]
Thank you, that is what I wanted to accomplish.
