### ISSUE TITLE
Rename the Downloads according to the the from the XML/RSS feed.

### ISSUE THREAD

**Issue by grisuthedragon** [dvehrs/podget#54]
Is there a possibility to rename the files after download such that the mp3 could be identified easily and for archiving? For example from one of my favorite podcasts one entry in the rss-xml looks like:
```
<item>
<title>
Urlaub in der Tupperdose – Grillen in der Unterhose
</title>
<link>
https://www.bremenzwei.de/audios/wischmeyers-stundenhotel-168.html
</link>
<description>
.....
</description>
<pubDate>Wed, 02 Dec 2020 21:00:00 +0100</pubDate>
<enclosure url="https://rbprogressivedl-a.akamaihd.net/clips/082/082964/082964_00340779_audio_stereo.mp3" length="72695085" type="audio/mpeg"/>
<guid isPermaLink="false">0dcef016-dec7-43a1-bc73-f8d0b7370021</guid>
<itunes:duration>01:15:43</itunes:duration>
</item>
```
And the resulting mp3 on the harddisk is only named `082964_00340779_audio_stereo.mp3` but I automatically want to have `DATE - TITLE.mp3`. (best would be configurable) I tried many Podcast download tools on Linux and Android an all of them only store the mp3 files as they got them without having the feature to automate it. Since want to let my NAS doing the job an I like to have an easy chance to find an episode in my archive, I would like to have it automatically renamed. 

Does podget can do this or is, as it seems, the feature also missing?

**Comment by dvehrs** [comment]
This is similar to the issue that Jon Harris raised in https://github.com/dvehrs/podget/issues/24 about using the pubDate tag. 

The problem with this request is making it work with how podget actually works.  Podget works by extracting all the enclosure tags from the file then sequentially downloading them (while checking for previously downloaded URLs).  

For what you propose to work, we would need to extract both the title and enclosure tags then hope that they are in the correct order and that title was never used for anything other than a feed item.   

Then when we find a solution for one feed, we need to verify that it will also work for others.  What about feeds that do not use a title tag?  

There may be a way to do it but I'm not sure I see it.   I will keep this request open and think about it.  Maybe I can find a solution or someone else will jump in with an idea.....

**Comment by 44213** [comment]
I see this especially with podcasts that are located on Anchor.
I don't want to give up podget because it runs perfect on my raspberry. 

Maybe someone knows another way to save the podcasts with title and date as a file name?

		<item>
			<title><![CDATA[**Crowd Sorcery #11**]]></title>
			<description><![CDATA[<p>Okay folks, going to quickly talk about 12 games in this episode with a suprising amount of expansions! :)</p>
]]></description>
			<link>https://anchor.fm/rahdo/episodes/Crowd-Sorcery-11-e1qepe8</link>
			<guid isPermaLink="false">042255c5-6217-48d1-942f-de9c99a27395</guid>
			<dc:creator><![CDATA[Richard Ham]]></dc:creator>
			<pubDate>Wed, 09 Nov 2022 16:30:57 GMT</pubDate>
			<enclosure url="**https://traffic.megaphone.fm/APO1064426045.mp3**" length="11845381" type="audio/mpeg"/>
			<itunes:summary>&lt;p&gt;Okay folks, going to quickly talk about 12 games in this episode with a suprising amount of expansions! :)&lt;/p&gt;
</itunes:summary>
			<itunes:explicit>No</itunes:explicit>
			<itunes:duration>00:16:27</itunes:duration>
			<itunes:image href="https://d3t3ozftmdmh3i.cloudfront.net/staging/podcast_uploaded_nologo/4228456/81316933823cb437.jpeg"/>
			<itunes:episodeType>full</itunes:episodeType>
		</item>
		<item>

**Comment by dvehrs** [comment]
OK I looked at a couple feeds on Anchor and they have the same problem that other feeds have.  The data we want is contained in two separate tags (the TITLE and ENCLOSURE tags).   Anchor also uses the TITLE tag several times before getting to the first ENCLOSURE tag.    So ensuring we have the right TITLE tag isn't as simple as it could be.

Then to keep things interesting Anchor uses the CDATA tag within the TITLE tag.  That would require an additional layer of parsing or the titles would not look like they do on the webpage.   This is interesting because I've seen a few sources that say CDATA is obsolete and not supported in HTML5 anyway.  But it is there so it would need to be handled. 

And if that wasn't enough, Anchor also allows the use of emoji in the titles.  Those would either need to be striped or you end up with a few characters that may not be included with the fonts installed on your system.  

Example TITLE tag:
```
<title><![CDATA[Anchor Morning Audio: Morning Coffee ☕ 11.03.2022 ⚓️🌊🎙🔊 ]]></title>
```

Now the ENCLOSURE tag for that TITLE looked like:
```
<enclosure url="https://anchor.fm/s/994580/podcast/play/60013204/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2Fexports%2F994580%2F60013204%2F28e121dad78cb3a2e731b4b7403c4359.m4a" length="27130234" type="audio/x-m4a"/>
```

So the filename for the downloaded file should be: 28e121dad78cb3a2e731b4b7403c4359.m4a

Not a very friendly filename.  

However if you are running Podget daily and using the OPT_FILENAME_RENAME_MDATE for this feed then the filename would be prefixed with the date and time it was downloaded.  So if it was a newly downloaded file today at 1:02pm, it would look like:

20221113_13hh02mm_28e121dad78cb3a2e731b4b7403c4359.m4a

Not necessarily a great filename either but at least it makes it a bit easier to see when an item is new and to sort downloaded files.

I'm still not sure I see a easy way to handle the TITLE and ENCLOSURE relationship to automatically rename files and as we can see from the Anchor example that relationship is just the beginning of what would need to be done.  

Any ideas?

Dave

**Comment by dvehrs** [comment]
OK I was wrong on one detail.   The filename for the downloaded file.

It appears Anchor is using an URL within an URL.   The second URL is not being parsed by Podget but included in it's entirely.

So the filename for the downloaded file is:
``` 
https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fproduction%2Fexports%2F994580%2F60013204%2F28e121dad78cb3a2e731b4b7403c4359.m4a
```

An even uglier filename....

**Comment by dvehrs** [comment]
OK, small improvement.   The feed I am testing from Anchor does offer a bit of a better filename if you use the OPT_FILENAME_LOCATION tag for the feed in your serverlist.

Instead of the long filename starting with 'https', you get the short filename that I first guessed:  
    28e121dad78cb3a2e731b4b7403c4359.m4a

Also in the case of files downloaded from Anchor when we use the OPT_FILENAME_RENAME_MDATE tag, it does not rename them with the date & time they were downloaded but in this case they are coming from a server that tells us their modification date.  So for this file, we end up with a filename like: 
    20221103_04h32m_28e121dad78cb3a2e731b4b7403c4359.m4a

Not great but closer to usable.

**Comment by dvehrs** [comment]
OK, I might have made some progress on this item.   It's currently in it's own branch and passes a few of the tests I have given it.  It currently only works for RSS feeds.  I have not begun on the atom feed conversion yet.

If you care to take a look or a test run, the stuff I am working on is in branch dev-titletag.

I started my testing with a feed from Anchor and one from The Linux Link.  Both appear to work.

There are two new options for the serverlist file for feeds to enable the use of the title tag.
  - OPT_FILENAME_RENAME_TITLETAG
  - OPT_FILENAME_RENAME_REVTITLETAG

The first is for when a feed lists the TITLE then ENCLOSURE tags.   The second is for when it lists ENCLOSURE first and TITLE second.  On my list of about 50 feeds, there are about 40 that use TITLE tags and almost all would need the first option.  I think, because about one third do not have a common part in the downloaded filename and the title that I can use to be sure they are in the right order so I will need to listen to those to determine which tag should be used.

Also I've run into a potential issue with removing any unicode symbols from the titles.  The simple methods I've worked out have an adverse effect on feeds with titles in anything other than English. 

I'm using a combination of options for the Anchor feed to make sure they work together.  So far so good.  The three different lines I have in my serverlist are:

```
#FEEDS:
# ------------------------------------------------------------------------------
http://thelinuxlink.net/tllts/tllts.rss LINUX The Linux Link OPT_FEED_PLAYLIST_NEWFIRST OPT_FILENAME_RENAME_TITLETAG

https://anchor.fm/s/994580/podcast/rss TEST Anchor FiremanRich OPT_FILENAME_RENAME_MDATE OPT_FILENAME_RENAME_TITLETAG
https://anchor.fm/s/994580/podcast/rss TEST Anchor FiremanRich OPT_FILENAME_LOCATION OPT_FILENAME_RENAME_MDATE OPT_FILENAME_RENAME_TITLETAG
```

Now obviously I don't use the two anchor examples at the same time, but either way it appears to work and it prefixes the filename with the modification date for the file.  Although in many cases the use of that tag is redundant because that feed often includes the date within the title.  Not always but frequently.  

Hopefully I will have more time for testing in the next couple weeks but like I said so far it looks good.

Dave

**Comment by dvehrs** [comment]
For an example, the Anchor feed items now look like:
```
20221213_04h15m_Anchor_Morning_Audio_Morning_Coffee_☕_12.13.2022_⚓🌊🎙🔊.m4a
20221220_04h29m_Anchor_Morning_Audio_Morning_Coffee_☕_12.20.2022_⚓🌊🎙🔊.m4a
20221222_04h20m_Anchor_Morning_Audio_Morning_Coffee_☕_12.22.2022_⚓🌊🎙🔊.m4a
```

For either of the two example serverlist lines above.

So definitely more usable that we had before.

Dave

**Comment by dvehrs** [comment]
OK, I've got ATOM feeds working just the way they did before the TITLE tag changes.  Unfortunately the example ATOM feeds I have are not good examples for developing this further. 

Dave

**Comment by dvehrs** [comment]
OK, time for another update.  I've been testing the dev branch and it's been almost perfect.  There was one minor issue that came up when testing on OpenBSD (apparently BSD tail does not support --lines like GNU tail so it's back to using -n, it works just slightly less readable).

Now I just finish testing on Debian Linux, FreeBSD, OpenBSD, and NetBSD with a old set of feeds to test.  Unfortunately I'm traveling for the next month and won't get home to do final testing until early March.  

If anyone is interesting the dev branch is pretty usable right now so feel free to give it a go.  I may be doing the same, I have a server that I can access remotely that downloads my nightly feeds for me that I should be able to update to this version and let it run.

Dave

**Comment by philrandal** [comment]
I've done limited testing but so far this looks good to me.

**Comment by dvehrs** [comment]
Thanks philrandal!

While I'm traveling, I've started some testing on a server that is at home (so remote from me now) for general crontab usage.  I'm using about twice as many feeds as I typically get on it and so far everything appears to work as planned.  

I have run into a minor issue but I'm not sure if it merits fixing.  For some feeds, the title will include commas and that can look a bit unusual when converted to a filename when it is part of a date.  At other times, it continues to make sense visually  so that's where I wonder if commas should be removed or not.  I'm leaning towards not removing them at this stage but curious about their effect on file systems other than EXT based ones.  This should probably be tested on FAT because of the number of devices that use it.  Although a quick gander at the restricted characters for FAT because of those that have special meaning with COMMAND.COM does not include the comma so maybe it will be alright and if I'm not mistaken all the problematic characters are already being caught by the badchars checks.   

Dave

**Comment by dvehrs** [comment]
OK time for a quick update!

I've released a new version of Podget with this in place.  If you download the lastest Master branch or get the release tagged "v0.9.1" then you can start using these new configuration options!

For the Debian users, there will be a short delay getting this into the apt repositories as the distribution is currently having a version freeze so only critical updates are allowed while they get a new version of Debian ready for release.  Since this update to Podget does not count as critical we get to wait for just a bit.
