### ISSUE TITLE
Old podcasts aren't being removed

### ISSUE THREAD

**Issue by erikellsinger** [dvehrs/podget#58]
This might be a configuration mistake on my part but old podcasts aren't being removed for me. I've set CLEANUP=1 and CLEANUP_DAYS=21 but I still have podcasts that were downloaded over a month ago.

If I run podget with bash -x I can see it runs this command to find files to cleanup:

find /mnt/podcasts/ -maxdepth 1 -type f -name '*.m3u'

Thing is, I don't use the playlist feature so there are not m3u files stored in my podcast directory. Am I missing something?

**Comment by theorbitofmercury** [comment]
I am having the same issue:
This is the cleanup section of my /home/pi/.podget/podgetrc/:

```
# Autocleanup.
# 0 == disabled
# 1 == delete any old content #MAW changed to 1
CLEANUP=1	

# Number of days to keep files.   Cleanup will remove anything
# older than this.
CLEANUP_DAYS=7
```
But I still have stuff from 2020 (todays date is 9/1/2020) although I run podget from crontab twice per day.
I do use the playlist .m3u feature and they are not cleaned up either.

**Comment by theorbitofmercury** [comment]
Just ran
```
podget --cleanup --cleanup_days 7 --cleanup_simulate
```
output
```
podget


Session file not found.  Creating podget.13537
Simulating cleanup, the following files will be removed when you run cleanup.

-------------------------------------------------
Build OPT_FEED_PLAYLISTs

Closing session and removing lock file.
```
so confirming nothing is being cleaned

**Comment by theorbitofmercury** [comment]
If I run
```
 podget --cleanup_days 7 --cleanup_simulate -vvv
```
(vvv gives verbose output)
I get 

podget

Library Directory:              /home/pi/POD
Session Directory:              /tmp/podget
Log Directory:                  /home/pi/POD/.LOG
Debug:                          Disabled - Delete temp files and reduced progress messages.

Session file not found.  Creating podget.30777
Simulating cleanup, the following files will be removed when you run cleanup.

-------------------------------------------------
Build OPT_FEED_PLAYLISTs

UTF-8 Loop running.

UTF-16 Loop running.
**No config file found, exiting loop.**

Closing session and removing lock file.

**Comment by dvehrs** [comment]
OK.  Starting from the top.

There appears to be some scant documentation for this feature.

There are two types of playlists.  Global playlists created for all new downloads that are not part of an individual feed playlist and those playlists that are dedicated to an individual feed.  

Individual feed playlists are deleted and rebuilt with every running so they will show the current set of files for that feed.  It's a bit more complicated than that because they remove old files and add new but the important bit is it happens every time podget runs.

On the other hand, global playlists are just created as files are downloaded and only include links to files downloaded that run.  If you run podget multiple times in a day then you will see multiple playlists for that day (by default these playlists are prefixed with 'New-').  Now cleanup of these playlist occurs when they are older than midnight of the cleanup_days setting.  So if I say cleanup_days = 1 then it was older than midnight yesterday (if today is 1/9 then cleanup older than 1/8 0:00).   Second issue is it only will cleanup playlists that are in the base of your Library directory.  It doesn't look for them anywhere else.

So to determine what is happening here, we need to see a playlist listing of your library directory:  ls -l /home/pi/POD/*.m3u    

That will tell us which it can find and how old they are but right now from the output you've given it doesn't appear to be finding any that are old enough.  

Dave

**Comment by theorbitofmercury** [comment]
OK thanks for getting back. I am less concerned with cleaning m3u files as they are small. I only use what you call global (2 per day as I run twice) . I am more interested in cleaning the individual podcast directories and their mp3 files as they are bigger so disk filling. 

I think its similar for the op who started this issue thread as he says he doesn't use the playlist feature.

**Comment by dvehrs** [comment]
OK, then we've got a slightly different function that what podget's automatic cleanup can handle.

If we want to remove files that aren't in a playlist that is probably something that needs to be done by hand.  Fortunately it can be done with one command and could even be set in crontab.

OK using the /mnt/podcasts as the library directory

To show the files with a modification date older than 7 days while ignoring the LOG directory.
```
find /mnt/podcasts ! -path "*/.LOG/*" -type f -mtime +7
```
If the list is what we wish to remove then add the '-delete' option to the end of the command.

Is that closer to what is needed for this job?

Dave

**Comment by theorbitofmercury** [comment]
OK Dave
Hope you don't mind but here is a copy of what you put on our discussion #57 https://github.com/dvehrs/podget/discussions/57

"Automatic cleanup uses the playlists to determine which files to remove. It does this because it is somewhat dangerous to use file modification (or change) dates because when we download from a few types of servers those dates are maintained from the original. This is good because it makes it easier to keep files in the order they were created but bad because it can make it more difficult for someone who has playlists disabled to clean out older files."

Thanks that clears up why cleanup is not working particularly if there is no playlists with option:
       -n, --no-playlist  ( Do not create M3U playlist of new items.)
or like in my case I am editing the "New-" playlists to make them compatible with mpd so the modification date gets changed as well as the path to the mp3's (as I add the full path prefix to each mp3 location)

So I will try your suggestion 
```
find /mnt/podcasts ! -path "*/.LOG/*" -type f -mtime +7
```
or something like this to clean up the individual directories together with their mp3's

Cheers Mike

**Comment by theorbitofmercury** [comment]
Ended up with this which deletes the individual directories and mp3 contents:
```
find /home/pi/POD ! -path "*/.LOG/*" -type d -mtime +6 -execdir rm -rf {} +
```
note -execdir is safer than -exec

**Warning: Be careful with the rm command when using with find. You may end up deleting unwanted data**.

Still to find something to remove old m3u files. Can't do it by modified date as this is updated every day by my editing #57 

Mike

**Comment by erikellsinger** [comment]
If you need to use the playlist feature for automatic removal of podcasts to work I think it should be mentioned as a comment in the config file in relation to CLEANUP_DAYS setting. As it is now it gives the impression that podcast files will always be automatically removed.

**Comment by dvehrs** [comment]
I made a small update to the default file that is created yesterday.  It's available in the DEV branch and will be included in the next release.  

From:
```
# Autocleanup.
```

To:
```
# Autocleanup of old playlists and the files they list.
```

It's still awkward but an improvement.  Always a challenge to stay pithy in configuration files.    

Dave

**Comment by erikellsinger** [comment]
Looks good, added a cron job so it's solved for now. But would be nice if podget could handle this also in the future.

**Comment by dvehrs** [comment]
Unfortunately as I explained to theorbitofmercury in a discussion thread ( https://github.com/dvehrs/podget/discussions/57 ) where he was mixing topics, this is not a simple thing for podget to do. 

Quote:
Automatic cleanup uses the playlists to determine which files to remove. It does this because it is somewhat dangerous to use file modification (or change) dates because when we download from a few types of servers those dates are maintained from the original. This is good because it makes it easier to keep files in the order they were created but bad because it can make it more difficult for someone who has playlists disabled to clean out older files.

Given these conditions, tracking which file was downloaded when so we know when to delete it requires some kind of log file that ends up being very like the playlist we already have.  If you or anyone else has a better solution then just work it out and submit a push request.

Dave

**Comment by dvehrs** [comment]
Uploaded a new version (0.8.8) with this change.   Closing this issue as any fixes anyone finds should come in as a push request.

Thanks,
Dave
