### ISSUE TITLE
Podcast is saved as a live stream

### ISSUE THREAD

**Issue by Bobabadabouskie** [dvehrs/podget#69]
I'm not sure why this is happening but this podcast http://feed.nashownotes.com/rss.xml is being saved as a live stream.

This is the live stream link that is used with vlc for example 
http://listen.noagendastream.com/noagenda

The rss.xml link works on other podcast players that I use.

When I use Podget to download the podcasts it never stops (until I manually kill it) because it starts downloading whatever is being streamed live and saves it as a file, noagenda

I can play that file and hear the recorded live stream.

Sorry if this isn't a clear enough description.

Let me know if there is anything I can do on my end.

Thanks.

**Comment by dvehrs** [comment]
This is interesting and I've never seen it before.  Unfortunately I do not see anything right off that will be easy to integrate into Podget to clear up the issue.

Let's start by describing how Podget works in general terms.

Podget starts by downloading the feed (in this case rss.xml) and then extracts all the enclosure tags from it and grabs the value of the URL tag.

In this case, what the enclosure tags are:
```
      <enclosure length="33" type="audio/mpeg" url="https://op3.dev/e/listen.noagendastream.com/noagenda"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1539-2023-03-19-Final.mp3" type="audio/mpeg" length="132155395"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1538-2023-03-16-Final.mp3" type="audio/mpeg" length="138443277"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1537-2023-03-12-Final.mp3" type="audio/mpeg" length="86245376"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1536-2023-03-09-Final.mp3" type="audio/mpeg" length="137177174"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1535-2023-03-05-Final.mp3" type="audio/mpeg" length="136046177"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1534-2023-03-02-Final.mp3" type="audio/mpeg" length="132986089"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1533-2023-02-26-Final.mp3" type="audio/mpeg" length="123993279"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1532-2023-02-23-Final.mp3" type="audio/mpeg" length="137488136"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1531-2023-02-19-Final.mp3" type="audio/mpeg" length="135863111"/>
      <enclosure url="https://op3.dev/e/mp3s.nashownotes.com/NA-1530-2023-02-16-Final.mp3" type="audio/mpeg" length="144807019"/>
```

Now if we look at the first line, we will see that it is a link to the live feed.  The only unusual thing I can see that maybe you could filter on is the 'length="33"' bit.   But I'm not sure if that is a good idea because I haven't been able to find any part of the RSS definition that says to use that for live items.   If we did use it, I'd be afraid that we were filtering out some items we'd rather keep.  

According to the RSS best practices, when the length of an item is unknown as we would expect for a live feed then the length should be 0 and not 33.  

Now for testing, I attempted to use Podget on the feed and it started on the noagenda file.  It was very slow to download that file.  Like an average of 20kb/s.   After downloaded 20MB, I stopped it.

Now if you look in the rss.xml file, there is a tag above the enclosure tag for noagenda that is a follows:
```
 <podcast:liveItem status="ended" start="2023-03-19T18:00:00.000Z" chat="https://kiwiirc.com/nextclient/irc.zeronode.net/#NoAgenda" end="2023-03-19T21:30:00.000Z">
```

That maybe what other podcast players are filtering on for the live items.  What is interesting for us is the 'status="ended"'.  Also interesting is that the start/end dates are the same as the very next URL from the enclosure tags.

If that is true that the "live" event has ended then Podget should reach the end of that item eventually and  mark the URL in its DONE file.  However that item downloads very slowly so it would be no fun to wait for and we can cheat to a quicker answer.

If you look inside the directory that Podget stores the files it downloads (defined as the DIR_LIBRARY in your podgetrc), within that directory there should be a hidden .LOG directory.  Within that directory open the "done" file then add the first URL to it on its own line.
```
https://op3.dev/e/listen.noagendastream.com/noagenda
<other URLs>
```

Then the next time you run Podget, it will skip that URL because it believes it has already downloaded it and proceed to the URL from the next enclosure tag.   For my testing this worked fine and it downloaded the remaining 10 files in the feed.  These files ranged from 122MB to 139MB and downloaded at an average of 6MB/s.  So all 10 files were downloaded in a few minutes.  

As long as the URL for the "live" item never changes, this should work for as long as you use Podget to download the feed.  Assuming you never lose your done file that is.

I'm going to leave this thread open for a while to see if any ideas come up to filter it.

Thanks and Good Luck,
Dave

**Comment by Bobabadabouskie** [comment]
Adding that url to the done file did in fact work for me too. Seems that would be the best workaround for the time being.

I'm thinking I will try to contact the podcast creator and seeing if they can/want to change anything on their side.

Thank you for the help, I will remember this little fix if I ever run into this problem again.

**Comment by dvehrs** [comment]
That explains why I could not find it in the RSS docs!  Thanks for the link!

I might be able to find a way to filter for those.   It the end it may end up similar to the ways I recently got TITLE and ENCLOSURE tags to play well together.   We've got a work around so I'm not going to rush into it but I definitely need to find time to review the podcast namespace docs to see what we can do better.

Thanks to all!
Dave

**Comment by dvehrs** [comment]
OK, got a quick update.

I was able to use much of what I've learned from handling TITLE tags and the filtering of the feed file to come up with a solution that appears to work.  I've uploaded it into the DEV branch for inclusion in the next version of Podget.  I've only done a small amount of testing so far but it seems to work without causing  issues with other feeds.  

At this stage Podget will ignore any podcast:liveitem tags and their data it finds.  This works just like adding the URL for the live feed to the done file but doesn't require the user to do anything.  This solution makes the most sense to me because Podget has never been the appropriate application for listening to live podcasts.  

If you want to test it, its in the DEV branch.  Just run Podget with the --force option to ignore what it is in the done file. 

Dave

**Comment by dvehrs** [comment]
OK, quick update.   

Released version 0.9.1 with these fixes so it is available for use!  Have fun.

There will be a small delay getting it into Debian as they are currently in an update freeze as part of moving to a new version of Debian.  Once the freeze is lifted, the new updates will be available via apt.

**Comment by Bobabadabouskie** [comment]
Very cool. Thanks much to you and @adamc199.

**Comment by Bobabadabouskie** [comment]
Sweet. Thanks again.
