### ISSUE TITLE
FILENAME_SUFFIX broken in newer versions

### ISSUE THREAD

**Issue by angoongo** [dvehrs/podget#9]
./podget: line 2155: CONTENT_FILENAME: unbound variable
works in podget-0.7.6 thats first one i tried

**Comment by dvehrs** [comment]
You're right.  I missed testing the use of FILENAME_SUFFIX on feeds that did not use the new CONTENT_DISPOSITION options.  That allowed a variable name issue to slip through.  Good catch!

It's now fixed in both the DEV and MASTER branches on Github.  A few more updates are needed on the DEV branch before we can merge with MASTER and consider an updated release.
